/**
 * Questionnaire Management Constants
 */

export {
  QUESTIONNAIRE_SECTIONS,
  INITIAL_FORM_DATA,
  REGIONS,
  REGION_CITIES,
  INDUSTRY_OPTIONS,
  CURRENCY_OPTIONS,
  JOB_TYPE_OPTIONS,
  AD_PLATFORM_OPTIONS,
  ATS_OPTIONS,
  RECRUITMENT_ASSESSMENT_OPTIONS,
  INTERNAL_STAFF_OPTIONS,
  REPORT_ACCESS_OPTIONS,
  LEADERSHIP_INTEREST_OPTIONS,
  WORKFLOW_STEPS_DEFAULT,
  WORKFLOW_PERSONNEL_OPTIONS,
  SUCCESS_CRITERIA_OPTIONS,
  TOTAL_SECTIONS,
} from './questionnaireFormConstants'
