import type { Metadata } from 'next'
import Link from 'next/link'
import {
  AlertTriangle,
  ArrowLeft,
  Clock,
  FileText,
  Scale,
  Shield,
  Users,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Terms of Service | Strategia',
  description:
    "These terms govern your use of Strategia's AI-powered HR platform.",
}

type TermsSection = {
  icon: LucideIcon
  title: string
  content: string
  items: string[]
}

const sections: TermsSection[] = [
  {
    icon: Users,
    title: 'Acceptance of Terms',
    content:
      'By accessing or using Strategia, you agree to be bound by these Terms of Service and all applicable laws and regulations.',
    items: [
      'You must be at least 18 years old to use this service',
      'You are responsible for maintaining the confidentiality of your account',
      'You agree to provide accurate and complete information',
      'You may not use the service for any unlawful purpose',
    ],
  },
  {
    icon: FileText,
    title: 'Use of Service',
    content:
      'Strategia provides AI-powered HR and recruitment services. Your use of these services is subject to the following conditions.',
    items: [
      'Candidates may upload resumes and complete assessments for job applications',
      'Employers may post jobs, review candidates, and conduct assessments',
      'All assessment results are generated by AI and should be used as one factor in hiring decisions',
      'You may not attempt to reverse engineer or manipulate assessment algorithms',
    ],
  },
  {
    icon: Shield,
    title: 'Intellectual Property',
    content:
      'All content, features, and functionality of Strategia are owned by Strategia and protected by intellectual property laws.',
    items: [
      'Assessment methodologies and AI models are proprietary',
      'You retain ownership of content you upload (resumes, job descriptions)',
      'You grant Strategia a license to process your content for service delivery',
      'You may not copy, modify, or distribute Strategia materials without permission',
    ],
  },
  {
    icon: AlertTriangle,
    title: 'Limitations of Liability',
    content:
      'Strategia provides services "as is" and makes no warranties regarding the accuracy of AI-generated insights.',
    items: [
      'Assessment results are recommendations, not guarantees of job fit',
      'Hiring decisions remain the sole responsibility of employers',
      'Strategia is not liable for employment outcomes',
      'Service availability may be subject to maintenance and updates',
    ],
  },
  {
    icon: Scale,
    title: 'Dispute Resolution',
    content:
      'Any disputes arising from these terms will be resolved through the following process.',
    items: [
      'Initial resolution through good-faith negotiation',
      'Mediation if negotiation is unsuccessful',
      'Binding arbitration as a final resolution method',
      'Governing law based on your jurisdiction of use',
    ],
  },
  {
    icon: Clock,
    title: 'Termination',
    content:
      'Either party may terminate the use of services under certain conditions.',
    items: [
      'You may delete your account at any time',
      'Strategia may suspend accounts that violate these terms',
      'Data retention after termination follows our Privacy Policy',
      'Certain provisions survive termination (IP rights, limitations of liability)',
    ],
  },
]

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#012236] text-white">
      <header className="border-b border-white/12 bg-[linear-gradient(135deg,#1C1C1C_0%,#00162E_24%,#003D6B_55%,#005072_100%)] py-24">
        <div className="mx-auto max-w-4xl px-6">
          <Link
            href="/"
            className="mb-8 inline-flex items-center gap-2 rounded-lg bg-[linear-gradient(135deg,#00C6C1_0%,#5CC8E8_100%)] px-4 py-2 text-sm font-semibold !text-[#012236] shadow-[0_14px_32px_-18px_rgba(92,200,232,0.9)] transition-all hover:-translate-y-0.5 hover:shadow-[0_18px_40px_-18px_rgba(92,200,232,1)]"
          >
            <ArrowLeft className="h-4 w-4" />
            <span>Back to Home</span>
          </Link>
          <span className="mb-4 block text-xs font-bold uppercase tracking-widest text-[#A5DCD0]">
            Legal
          </span>
          <h1 className="mb-6 font-serif text-4xl !text-white md:text-5xl">
            Terms of Service
          </h1>
          <p className="max-w-2xl text-lg font-light text-white/88">
            These terms govern your use of Strategia&apos;s AI-powered HR
            platform. Please read them carefully before using our services.
          </p>
          <p className="mt-4 text-sm text-[#A5DCD0]">
            Last updated: December 2024
          </p>
        </div>
      </header>

      <main className="bg-[radial-gradient(900px_520px_at_85%_0%,rgba(0,198,193,0.14),transparent_60%),radial-gradient(740px_480px_at_10%_20%,rgba(92,200,232,0.10),transparent_60%)] py-16">
        <div className="mx-auto max-w-4xl space-y-12 px-6">
          {sections.map((section) => (
            <Section key={section.title} section={section} />
          ))}

          <section className="rounded-xl border border-[#00C6C1]/35 bg-[linear-gradient(135deg,rgba(0,198,193,0.14)_0%,rgba(92,200,232,0.10)_100%)] p-8 text-center">
            <h2 className="mb-3 font-serif text-xl !text-white">
              Questions About These Terms?
            </h2>
            <p className="mb-4 leading-relaxed text-white/86">
              If you have any questions about these Terms of Service, please
              contact us.
            </p>
            <a
              href="mailto:legal@strategia.ai"
              className="font-semibold text-[#A5DCD0] transition-colors hover:text-[#5CC8E8]"
            >
              legal@strategia.ai
            </a>
          </section>
        </div>
      </main>

      <footer className="border-t border-white/12 bg-[#012236] py-12">
        <div className="mx-auto flex max-w-4xl flex-col items-center justify-between gap-4 px-6 sm:flex-row">
          <p className="text-sm text-white/70">
            © {new Date().getFullYear()} Strategia. All rights reserved.
          </p>
          <div className="flex flex-col items-center gap-4 sm:flex-row">
            <Link
              href="/privacy-policy"
              className="text-sm font-medium text-[#A5DCD0] transition-colors hover:text-[#5CC8E8]"
            >
              Privacy Policy
            </Link>
            <Link
              href="/"
              className="inline-flex items-center gap-2 rounded-lg bg-[linear-gradient(135deg,#00C6C1_0%,#5CC8E8_100%)] px-6 py-2.5 text-sm font-semibold !text-[#012236] shadow-[0_16px_34px_-18px_rgba(92,200,232,0.95)] transition-all hover:-translate-y-0.5 hover:shadow-[0_22px_44px_-18px_rgba(92,200,232,1)]"
            >
              Return to Home
            </Link>
          </div>
        </div>
      </footer>
    </div>
  )
}

function Section({ section }: { section: TermsSection }) {
  const Icon = section.icon

  return (
    <section className="rounded-xl border border-white/15 bg-white/[0.075] p-8 shadow-[0_28px_70px_-45px_rgba(0,0,0,0.75)] backdrop-blur-sm transition-colors hover:border-[#00C6C1]/45">
      <div className="mb-6 flex items-start gap-4">
        <Icon className="mt-1 h-8 w-8 flex-shrink-0 stroke-1 text-[#A5DCD0]" />
        <div>
          <h2 className="mb-3 font-serif text-xl !text-white">
            {section.title}
          </h2>
          <p className="leading-relaxed text-white/86">{section.content}</p>
        </div>
      </div>
      <ul className="ml-12 space-y-3">
        {section.items.map((item) => (
          <li key={item} className="flex items-start gap-3">
            <span className="mt-2 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-[linear-gradient(135deg,#00C6C1,#5CC8E8)]" />
            <span className="text-sm leading-relaxed text-white/86">
              {item}
            </span>
          </li>
        ))}
      </ul>
    </section>
  )
}
